"""
main.py
Location: back/agents/main.py

Run:
    cd back/agents
    uvicorn main:app --reload

Test:
    curl -X POST http://localhost:8000/chat \
         -H "Content-Type: application/json" \
         -d '{"message": "What are Tatkal cancellation charges?"}'

Docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel

from router import detect_intent
from policy_rag import answer_policy_query
from general_agent import handle_general_query

# ---------------------------------------------------------------------
# Future agent imports — uncomment as each module is built
# ---------------------------------------------------------------------
# from tourism_agent import recommend_packages   # Step 8a
# from trip_planner  import plan_trip            # Step 8b
# from refund_agent  import handle_refund        # Step 5


# =====================================================================
# APP INITIALISATION
# =====================================================================

app = FastAPI(
    title="IRCTC AI Assistant",
    description="AI-powered backend for IRCTC customer support.",
    version="1.0.0",
)


# =====================================================================
# CORS — allows the React frontend to call this API
#
# localhost:3000 = Create React App default port
# localhost:5173 = Vite default port
# Add your deployed frontend URL here when you go to production.
# =====================================================================


app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# =====================================================================
# GLOBAL EXCEPTION HANDLER
#
# Catches any unhandled exception anywhere in the app.
# User never sees a raw Python traceback or a 500 HTML error page.
# They always get a clean JSON response they can display in the UI.
# =====================================================================

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    print(f"[main] Unhandled exception: {str(exc)[:200]}")
    return JSONResponse(
        status_code=200,          # 200 so the frontend always parses the body
        content={
            "reply": "Something went wrong. Please try again.",
            "intent": "error",
        },
    )


# =====================================================================
# REQUEST / RESPONSE MODELS
# =====================================================================

class ChatRequest(BaseModel):
    message: str


class ChatResponse(BaseModel):
    reply: str
    intent: str


# =====================================================================
# HEALTH CHECK
# =====================================================================

@app.get("/")
def health():
    return {"status": "running", "service": "IRCTC AI Assistant"}


# =====================================================================
# /chat ENDPOINT
# =====================================================================

@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Main chat endpoint. Accepts a user message, routes it to the
    correct agent, and returns the reply with the detected intent.

    Routing logic:
        policy_query    → policy_rag  (falls back to general_agent if None)
        refund_issue    → general_agent for now  [plug in refund_agent later]
        tourism_package → general_agent for now  [plug in tourism_agent later]
        trip_planning   → general_agent for now  [plug in trip_planner later]
        general_support → general_agent
        anything else   → general_agent
    """

    # ------------------------------------------------------------------
    # Step 1: Validate input
    # ------------------------------------------------------------------
    message = request.message.strip() if request.message else ""
    if not message:
        return ChatResponse(
            reply="Please type your question — I'm here to help with Indian Railways!",
            intent="empty",
        )

    # ------------------------------------------------------------------
    # Step 2: Detect intent
    # ------------------------------------------------------------------
    try:
        router_result = detect_intent(message)
        intent        = router_result.get("intent", "general_support")
        confidence    = router_result.get("confidence", "low")
        source        = router_result.get("source", "unknown")
        print(f"[main] intent={intent} | confidence={confidence} | source={source}")
    except Exception as e:
        print(f"[main] Router failed: {str(e)[:100]}")
        intent = "general_support"

    # ------------------------------------------------------------------
    # Step 3: Route to the correct agent
    # ------------------------------------------------------------------

    reply: str | None = None

    if intent == "policy_query":
        # policy_rag returns None when similarity score < threshold
        # (question is out of scope for the policy knowledge base).
        # In that case, fall through to general_agent automatically.
        reply = answer_policy_query(message)
        if reply is None:
            print("[main] policy_rag returned None → falling back to general_agent")
            reply = handle_general_query(message)

    elif intent == "refund_issue":
        # ── Future: plug in refund_agent ──────────────────────────────
        # from refund_agent import handle_refund
        # reply = handle_refund(message)
        # ─────────────────────────────────────────────────────────────
        reply = handle_general_query(message)

    elif intent == "tourism_package":
        # ── Future: plug in tourism_agent ─────────────────────────────
        # from tourism_agent import recommend_packages
        # reply = recommend_packages(message)
        # ─────────────────────────────────────────────────────────────
        reply = handle_general_query(message)

    elif intent == "trip_planning":
        # ── Future: plug in trip_planner ──────────────────────────────
        # from trip_planner import plan_trip
        # reply = plan_trip(message)
        # ─────────────────────────────────────────────────────────────
        reply = handle_general_query(message)

    else:
        # general_support + any unknown intent
        reply = handle_general_query(message)

    # ------------------------------------------------------------------
    # Step 4: Safety net — reply must never be None or empty
    # ------------------------------------------------------------------
    if not reply or not reply.strip():
        reply = "I couldn't generate an answer. Please try rephrasing or visit irctc.co.in."

    return ChatResponse(reply=reply, intent=intent)